"""add asset_id to ingest_jobs

Revision ID: 468cc2fffe0f
Revises: b8de4bed79b2
Create Date: 2026-06-23 09:57:53.105885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468cc2fffe0f'
down_revision: Union[str, None] = 'b8de4bed79b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_duration')
        batch_op.create_index(batch_op.f('ix_assets_duration_sec'), ['duration_sec'], unique=False)

    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.drop_column('asset_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_duration_sec'))
        batch_op.create_index('ix_assets_duration', ['duration_sec'], unique=False)

    # ### end Alembic commands ###
