"""Add is_favorite to Asset

Revision ID: 6b49008d5be4
Revises: cf2124132223
Create Date: 2026-06-26 17:39:11.579744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b49008d5be4'
down_revision: Union[str, None] = 'cf2124132223'
branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
        batch_op.alter_column('ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('assets_file_path_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_assets_duration_sec'), ['duration_sec'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_file_name'), ['file_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_file_path'), ['file_path'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_ingested_at'), ['ingested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_is_favorite'), ['is_favorite'], unique=False)

    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index('ix_scene_asset_id', ['asset_id'], unique=False)
        batch_op.create_index('ix_scene_searchable_text', ['searchable_text'], unique=False)
        batch_op.create_index('ix_scene_timestamp', ['timestamp_start_sec'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_asset_id'))
        batch_op.drop_index('ix_scene_timestamp')
        batch_op.drop_index('ix_scene_searchable_text')
        batch_op.drop_index('ix_scene_asset_id')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_is_favorite'))
        batch_op.drop_index(batch_op.f('ix_assets_ingested_at'))
        batch_op.drop_index(batch_op.f('ix_assets_file_path'))
        batch_op.drop_index(batch_op.f('ix_assets_file_name'))
        batch_op.drop_index(batch_op.f('ix_assets_duration_sec'))
        batch_op.create_unique_constraint('assets_file_path_key', ['file_path'])
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
