"""add title to assets

Revision ID: 6d505627b4a2
Revises: 4e7c1b2a9f21
Create Date: 2026-06-22 07:07:47.879050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d505627b4a2'
down_revision: Union[str, None] = '4e7c1b2a9f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('assets', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('thumbnail_s3_key', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('video_s3_key', sa.String(), nullable=True))
    op.alter_column('assets', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('assets_file_path_key', 'assets', type_='unique')
    op.create_index('ix_assets_duration', 'assets', ['duration_sec'], unique=False)
    op.create_index('ix_assets_file_name', 'assets', ['file_name'], unique=False)
    op.create_index(op.f('ix_assets_file_path'), 'assets', ['file_path'], unique=True)
    op.create_index('ix_assets_ingested_at', 'assets', ['ingested_at'], unique=False)
    op.add_column('scenes', sa.Column('searchable_text', sa.Text(), nullable=True))
    op.add_column('scenes', sa.Column('semantic_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scenes', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scenes', sa.Column('detected_objects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scenes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('scenes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_scene_asset_id', 'scenes', ['asset_id'], unique=False)
    op.create_index('ix_scene_searchable_text', 'scenes', ['searchable_text'], unique=False)
    op.create_index('ix_scene_timestamp', 'scenes', ['timestamp_start_sec'], unique=False)
    op.create_index(op.f('ix_scenes_asset_id'), 'scenes', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenes_asset_id'), table_name='scenes')
    op.drop_index('ix_scene_timestamp', table_name='scenes')
    op.drop_index('ix_scene_searchable_text', table_name='scenes')
    op.drop_index('ix_scene_asset_id', table_name='scenes')
    op.drop_column('scenes', 'updated_at')
    op.drop_column('scenes', 'created_at')
    op.drop_column('scenes', 'detected_objects')
    op.drop_column('scenes', 'tags')
    op.drop_column('scenes', 'semantic_metadata')
    op.drop_column('scenes', 'searchable_text')
    op.drop_index('ix_assets_ingested_at', table_name='assets')
    op.drop_index(op.f('ix_assets_file_path'), table_name='assets')
    op.drop_index('ix_assets_file_name', table_name='assets')
    op.drop_index('ix_assets_duration', table_name='assets')
    op.create_unique_constraint('assets_file_path_key', 'assets', ['file_path'])
    op.alter_column('assets', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('assets', 'video_s3_key')
    op.drop_column('assets', 'thumbnail_s3_key')
    op.drop_column('assets', 'description')
    op.drop_column('assets', 'title')
    op.drop_column('assets', 'updated_at')
    # ### end Alembic commands ###
