"""add_pgvector

Revision ID: 8ddd86ffa633
Revises: 163d2d28d056
Create Date: 2026-06-16 01:18:27.467871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '8ddd86ffa633'
down_revision: Union[str, None] = '163d2d28d056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Try to create vector extension (only works on postgres)
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
        
    op.alter_column('assets', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('ingest_jobs', 'job_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('scenes', sa.Column('keyframe_s3_key', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.alter_column('scenes', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('scenes', 'asset_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenes', 'asset_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('scenes', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('scenes', 'embedding')
    op.drop_column('scenes', 'keyframe_s3_key')
    op.alter_column('ingest_jobs', 'job_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('assets', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
